#pragma once

#include "NativeGameplayTags.h"

namespace BaseGameplayTag
{	//Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Turn);
}