#pragma once

#include "NativeGameplayTags.h"

namespace BaseGameplayTag
{	//Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Punch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LeftLeaning);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RightLeaning);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CameraTransition);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RightShouldering);
	
	
	
	
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Inventory);

	// Weapon Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Zoom);

	// Weapon Action Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Zoom);

	// Weapon Event Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_ReloadEnd);

	// Hit Event Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Action_Hit);
	
	
	
	
	
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Turn);

	// Data Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	
}