#pragma once

#include "NativeGameplayTags.h"

namespace BaseGameplayTag
{	//Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Punch);

	// Weapon Input Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Zoom);

	// Weapon Action Tag
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Equip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_UnEquip);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Fire);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Reload);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_ChangeFireMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Action_Zoom);
	
	
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Turn);
}